<img src="https://github.com/4GeeksAcademy/machine-learning-prework/blob/main/02-numpy/assets/numpy_logo.png?raw=1" alt="logo" width="400"/>

## Introduction to numpy

NumPy stands for 'Numerical Python'. It is an open-source Python library used to perform various mathematical and scientific tasks. It contains multi-dimensional arrays and matrixes, along with many high-level mathematical functions that operate on them. It contains among other things:

→ a powerful N-dimensional array object.

→ sophisticated (broadcasting) functions.

→ tools for integrating C/C++ and Fortran code.

→ useful linear algebra, Fourier transform, and random number capabilities.

## Installing NumPy
When you want to work with numpy locally, you should run the following commands:

You can install NumPy with:\
`pip install numpy`\
or\
`conda install numpy`

In our case, 4Geeks have prepared all the environment in order that you can work comfortably.

## Why should we use NumPy?

Numpy is a library that performs numerical calculations in python. We will use it mainly because it allows us to create, modify matrixes, and do operations on them with ease.

NumPy is like Pandas, Matplotlib or Scikit-Learn. It is one of the packages that you cannot miss when you are studying Machine Learning. Mainly because this library provides a matrix data structure that has some benefits over regular Python lists. Some of these benefits are: being more compact, quicker access to reading and writing articles, more convenient and efficient.

For example, we will see later in the bootcamp that working with images is dealing with three-dimensional matrixes as large as 3840 x 2160, which means we will have 3×3840×2160 = 24883200 entries!!! 😱😱😱.

Working with matrixes of that magnitude is practically impossible to carry out with lists and dictionaries if one wants to have an efficient and fast programming.

#### Exercise: Import the numpy package under the name `np` (★☆☆)

`numpy` is commonly imported as `np` so we highly recommend to put this alias.

In [ ]:
import numpy as np

## What is an array and why it is important for Machine Learning?

An array is a data structure consisting of a collection of elements (values or variables), each identified by at least one index or key.


![alt text](assets/1D.png "1D")

An array is known as the central data structure of the Numpy library; it can also be of several dimensions. For example, neural networks sometimes deal with 4D arrays.

Later on, we are also going to use another kind of arrays called: Tensors.

![alt text](./assets/3D.png "3D")

#### Exercise: Print the version and configuration of numpy (★☆☆)

You can print the version of any package of Python using `name_of_package.__version__`

In [ ]:
import numpy as np
print(np.__version__)

1.21.3


#### Exercise: Create a null vector of size 10 (★☆☆)

A `null vector` is an array of zeros (`0`), also called `initialization vector`.

>Check de function `np.zeros` (https://numpy.org/doc/stable/reference/generated/numpy.zeros.html)

In [ ]:
np.zeros(0)

array([], dtype=float64)

#### Exercise: Create a vector of ones with size 10 (★☆☆)

>Check de function `np.ones` (https://numpy.org/doc/stable/reference/generated/numpy.ones.html)

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Exercise: Create an 1D array with a specific start value, end value, and number of values (★☆☆)

>Check the function `np.linspace` (https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)

In [ ]:
np.linspace(1,2,10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

#### Run: Create a vector (1D array) with random integers from 10 to 49 and dimension 1x35 (★☆☆)

When `dimension` is expressed `1x35` it means: One dimension array with 35 items (length=35).

>Check the function `np.random` which allows you to create random arrays (https://numpy.org/doc/1.16/reference/routines.random.html)

In [7]:
import numpy as np

## 10 random numbers between (0, 1)
print(np.random.random(10)) 

[0.38594301 0.64031795 0.83707126 0.73205968 0.06798739 0.71747712
 0.44385982 0.10279507 0.38987376 0.99427282]


In [8]:
## Two ways to create numbers with normal distribution
print(np.random.rand(10)) # 10 random values with distribution N(0,1)
print(np.random.normal(loc = 0, scale = 1, size = 10)) # 10 random values with distribution N(0,1)

[0.73652549 0.11893842 0.53053486 0.77015469 0.40654315 0.32925097
 0.08885263 0.9977666  0.86350702 0.19018974]
[ 0.77681385  0.90547889 -0.13112258  0.04123816 -0.4322505   0.48882641
  0.31945336  0.40462334 -0.53359609 -0.86279604]


In [9]:
## Did you notice the difference between both functions? 
print(np.random.normal(loc = -5, scale = 33, size = 10)) # 10 random values with distribution N(-5,33)

[-11.25763464   7.79005266   2.22047944  41.24902863  29.19842731
   6.69302966  -7.59682931  16.7729069   72.90892732  22.68875839]


In [10]:
## 10 random values with uniform distribution. That means, all values have the same probability
print(np.random.uniform(-30,100,10)) # All values are between -30 and 100.

[ 72.97674568  91.48526875 -29.0300693   20.78971941  83.1399358
  27.05183222  52.25337626  12.73012856  13.97174654  93.41266697]


In [11]:
# 10 integers values between 0 and 100.
print(np.random.randint(0, 100, 10))

[ 1  7 75 28 78 58 81 67 22 26]


In [12]:
# 10 random values with Chi distribution with 5 degrees of freedom
print(np.random.chisquare(5,10))

[3.75227237 1.51171417 2.37829243 4.61569928 2.22805194 2.58528485
 6.16287177 6.62341727 3.2215087  5.92980883]


The above examples are the most common distribution and random values you will learn throughout the bootcamp. Now, let's deal with those arrays.

#### Exercise: Reverse one of the last vector we created before (first element becomes last) (★☆☆)
Try with `[::-1]`

In [20]:
a= np.linspace(1,2,10)
a
res = a[::-1]
res


array([2.        , 1.88888889, 1.77777778, 1.66666667, 1.55555556,
       1.44444444, 1.33333333, 1.22222222, 1.11111111, 1.        ])

#### Exercise: Create a 5x5 identity matrix (★☆☆)

>Check the function `np.eye`(https://numpy.org/devdocs/reference/generated/numpy.eye.html)

In [21]:
a=np.eye(5, dtype=int)
a


array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

#### Exercise: Find indexes of non-zero elements from [1,2,0,0,4,0] (★☆☆)

>Check the function `where`(https://numpy.org/devdocs/reference/generated/numpy.where.html)

In [31]:
import numpy as np
li = [1,2,0,0,4,0]
arr = np.array(li)
li_new = np.nonzero(arr)
li_list = np.nonzero(arr)[0]
print(li_new)
print(li_list)

(array([0, 1, 4]),)
[0 1 4]


#### Exercise: Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

>Check the function `min` (https://numpy.org/devdocs/reference/generated/numpy.where.html) and `max` (https://numpy.org/devdocs/reference/generated/numpy.max.html)

In [32]:
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.38563285 0.92015871 0.15172885 0.55366451 0.55261279 0.12531233
  0.07143094 0.23591305 0.85194729 0.35517557]
 [0.38429127 0.76549136 0.78201793 0.60301944 0.4747095  0.31595291
  0.93160153 0.43938938 0.13170027 0.08804872]
 [0.37728559 0.9860869  0.87534524 0.93858393 0.7864612  0.32250441
  0.61746665 0.51726904 0.94451874 0.77057938]
 [0.64697799 0.89053939 0.56232366 0.12803439 0.21065492 0.00446655
  0.78746757 0.8718488  0.59692584 0.75046057]
 [0.13720956 0.02512028 0.59606692 0.57239396 0.66454625 0.52720623
  0.5198421  0.45773285 0.79198474 0.76029799]
 [0.90536338 0.59305816 0.10223661 0.65760401 0.56977057 0.11717749
  0.87326707 0.36510002 0.73282976 0.09631921]
 [0.06222    0.29290484 0.91725947 0.27764376 0.17384134 0.70499681
  0.01978265 0.66255579 0.82212796 0.38403073]
 [0.67082811 0.56061653 0.23775534 0.6408765  0.26178033 0.87824232
  0.6819433  0.78798243 0.42257324 0.1848121 ]
 [0.63216269 0.01597181 0.38953189 0.56368523 0.64831112 0.09842

#### Exercise: Create a random vector of size 30 and find the mean value (★☆☆)

In [33]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
b=np.mean(a)
print(b)

Original array:
[0.98723417 0.48645191 0.96889288 0.66478189 0.42520221 0.02898468
 0.99785818 0.61975837 0.36982707 0.19876136]
0.2


#### Exercise: Define a function with your date of birth (yyyy/mm/dd) as imput, that returns a random array with the following dimensions: (★★☆)

$$yyyy-1900 \times |mm - dd|$$

## What is the difference between Python List and a Numpy Array?

- Python list can contain elements with different data types, while Numpy Array‘s elements are always homogeneous (same data types).

- Numpy arrays are faster and more compact than Python lists.

## Why Numpy Arrays are faster than Lists?

- Numpy Arrays use fixed memory to store data and less memory than Python lists.

- Contiguous memory allocation in Numpy Arrays.

#### Exercise: Convert the list `my_list = [1, 2, 3]` to numpy array (★☆☆)

In [35]:

my_list = [1, 2, 3]
arr = np.array(my_list)
print(arr)

[1 2 3]


#### Exercise: Convert the tuple `my_list = (1, 2, 3)` to numpy array (★☆☆)

In [50]:
import numpy as np

tup = (1, 2, 3)
print(tup)
print(type(tup))

print("After converting Python tuple to array")

arr = np.asarray(tup)
print(arr)
print(type(arr))

(1, 2, 3)
<class 'tuple'>
After converting Python tuple to array
[1 2 3]
<class 'numpy.ndarray'>


#### Exercise: Convert the list of tuples `my_list = [(1,2,3), (4,5)]` to numpy array (★☆☆)

In [55]:
import numpy as np

tup = [(1,2,3), (4,5)]
print(tup)
print(type(tup))

print("After converting Python tuple to array")

for i in range(len(tup)):
  arr = np.asarray(tup[i])
  print(arr)
  print(type(arr))

[(1, 2, 3), (4, 5)]
<class 'list'>
After converting Python tuple to array
[1 2 3]
<class 'numpy.ndarray'>
[4 5]
<class 'numpy.ndarray'>


#### Exercise: Resize a random array of dimensions 5x12 into 12x5 (★☆☆)

>Check `reshape` from `numpy` (https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)

In [39]:
import numpy as np
x = np.random.random((5,12))
print("Original Array:")
print(x)

y= np.reshape(x, (12, 5))
print(y)

Original Array:
[[0.99334305 0.58346325 0.40500992 0.12667983 0.76173261 0.2001004
  0.4271744  0.06659958 0.99867289 0.17100721 0.32504246 0.83939769]
 [0.77825464 0.56956551 0.57837145 0.65399012 0.79900566 0.20527136
  0.02282999 0.98764049 0.00559234 0.86315085 0.68193324 0.84818875]
 [0.105872   0.0105259  0.6632645  0.63659657 0.24589543 0.4330015
  0.15246437 0.81518799 0.90051072 0.94264454 0.71317296 0.59514961]
 [0.95551835 0.13561934 0.51838576 0.0153248  0.19622676 0.93734346
  0.87310654 0.26552882 0.68633954 0.91276462 0.64260682 0.99868193]
 [0.87184735 0.43093429 0.53481123 0.01575272 0.40938372 0.3972402
  0.1879487  0.34458433 0.74886743 0.27221683 0.61092734 0.17062769]]
[[0.99334305 0.58346325 0.40500992 0.12667983 0.76173261]
 [0.2001004  0.4271744  0.06659958 0.99867289 0.17100721]
 [0.32504246 0.83939769 0.77825464 0.56956551 0.57837145]
 [0.65399012 0.79900566 0.20527136 0.02282999 0.98764049]
 [0.00559234 0.86315085 0.68193324 0.84818875 0.105872  ]
 [0.0105259

#### Exercise: Create a function that normalize a 5x5 random matrix (★☆☆)

>Remember from probability (https://en.wikipedia.org/wiki/Normalization_(statistics)) that :
$$ x_{norm} = \frac{x - \bar{x}}{\sigma}$$


In [40]:
import numpy as np
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.61644361 0.49901237 0.02967096 0.11799495 0.53134422]
 [0.13577298 0.58090883 0.52086835 0.15759716 0.67789666]
 [0.98396612 0.07377195 0.69450338 0.27410938 0.92255279]
 [0.82804637 0.97216482 0.24942753 0.36334314 0.02255487]
 [0.1599127  0.37870806 0.60792957 0.91496999 0.76805969]]
After normalization:
[[0.61772601 0.49558136 0.00740171 0.09927082 0.52921094]
 [0.11776241 0.58076496 0.51831459 0.14046256 0.68164564]
 [1.         0.05327281 0.69891892 0.26165131 0.93612169]
 [0.837822   0.98772502 0.23597879 0.3544667  0.        ]
 [0.14287105 0.37044832 0.60887024 0.92823453 0.77542761]]


## Stacking numpy arrays

Stacking is used to join a sequence of same dimension arrays along a new axis.

`numpy.stack(arrays,axis)` : It returns a stacked array of the input arrays which has one more dimension than the input arrays.

### You have two ways to do it:


![alt text](./assets/stack.jpeg "stack")


### or


![alt text](./assets/stack2.jpeg "stack")




#### Exercise: Generate two random arrays with integers and apply the stacking using `stack` (★★☆)

[7 9 3] [9 0 6]


#### Exercise: Generate two random arrays with integers and apply the stacking using `hstack` and `vstack` (★★☆)

## Basic maths in numpy

You can make typical math operations like:

- Addition,Subtraction,Multiplication and Division between two arrays using numpy.
- Operation on arrays using sum() & cumsum() function.
- Minimum and Maximum value from an array.
- Exponent/Power , Square Root and Cube Root functions.

or even apply common trigonometric functions:

- `numpy.sin()`:  Sine (x) Function
- `numpy.cos()`: Cosine(x) Function
- `numpy.tan()`: Tangent(x) Function
- `numpy.sinh()`: Hyperbolic Sine (x) Function
- `numpy.cosh()`: Hyperbolic Cosine(x) Function
- `numpy.tanh()`: Hyperbolic Tangent(x) Function
- `numpy.arcsin()`: Inverse Sine(x) Function
- `numpy.arccos()`: Inverse Cosine(x) Function
- `numpy.arctan()`: Inverse Tangent(X) Function
- `numpy.pi`: Pi value π
- `numpy.hypot(w,h)`: For calculating Hypotenuse $c = \sqrt{(w^2 + h^2)}$
- `numpy.rad2deg()`: Radians to degrees
- `numpy.deg2rad()`: Degrees to radians

i#### Exercise: Generate two random 8 - dimensional vectors and apply the most common operation between vectors:  addition, substraction, multiplication, division(★☆☆)

>Check the math functions here: https://numpy.org/doc/stable/reference/routines.math.html

In [73]:
import numpy as np
x=np.random.randint(0, 100, 8)
y=np.random.randint(0, 100, 8)
print(x)
print(y)
print(np.add(x, y))
print(np.subtract(x, y))
print(np.matmul(x,y))
print(np.dot(x,y))
print(np.multiply(x,y))
print(np.divide(x,y))




[80  0 43 26 15 37 21 99]
[66 45 34 11 44  7 68 34]
[146  45  77  37  59  44  89 133]
[ 14 -45   9  15 -29  30 -47  65]
12741
12741
[5280    0 1462  286  660  259 1428 3366]
[1.21212121 0.         1.26470588 2.36363636 0.34090909 5.28571429
 0.30882353 2.91176471]


#### Exercise: Generate two random matrices with dimensions between 5 and 10. For example, try 5x7 vs 8x9. Were you able to do the matrix multiplication? why? (★★☆) 

In [40]:
#importante que el numero de columnas de primera matriz sea igual filas de segunda matriz

#### Exercise: Given 2 numpy arrays as matrices, output the result of multiplying the 2 matrices (as a numpy array) Were you able to do the matrix multiplication? (★★☆) 

$$ a = \left(\begin{matrix}
0 & 1 & 2\\ 
3 & 4 & 5\\ 
6 & 7 & 8
\end{matrix}\right)$$

$$ b = \left(\begin{matrix}
2 & 3 & 4\\ 
5 & 6 & 7\\ 
8 & 9 & 10
\end{matrix}\right)$$




In [48]:
import numpy as np
a =np.array([[0,1,2],
            [3,4,5],
            [6,7,8]])
b=np.array([[2,3,4],
           [5,6,7],
           [8,9,10]])

print(np.matmul(a,b))#multiplicacion fila columna
print(np.dot(a,b))
print(np.multiply(a,b))#las mismas dimensiones exactas en toda la matriz para usar esta funcion



[[ 21  24  27]
 [ 66  78  90]
 [111 132 153]]
[[ 21  24  27]
 [ 66  78  90]
 [111 132 153]]
[[ 0  3  8]
 [15 24 35]
 [48 63 80]]


#### Exercise: Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★★☆)

In [49]:
import numpy as np
x= np.random.random((5,3))
y= np.random.random((3,2))

print(np.dot(x,y))

[[0.82951633 0.61721747]
 [0.76474234 0.77587722]
 [0.86067882 0.70252146]
 [0.7824984  0.97448521]
 [1.13123602 1.10290995]]


## Data types

Do you think the following preposition is true?

`8==8`

Surely you will definetely say yes, which is true mathematically, but computationally it is not always the same, at least in terms of memory. For example, run the following cell:

In [74]:
import sys

# int64
x = np.array(123)
print("int64: " + str(sys.getsizeof(x)))

# int8
x = np.array(123,dtype=np.int8)
print("int8: " + str(sys.getsizeof(x)))

# float32
x = np.array(123,dtype=np.float32)
print("float32: " + str(sys.getsizeof(x)))

int64: 96
int8: 89
float32: 92


#### It turns out that there are many computational representation of the same number and you can create arrays with different Data Types (dtypes) depending on what you need:

- Boolean : `np.bool_`
- Char : `np.byte`
- Short : `np.short`
- Integer : `np.short`
- Long : `np.int_`
- Float : `np.single`&np.float32`
- Double :`np.double`&`np.float64`
- `np.int8`: integer (-128 to 127)
- `np.int16`:integer( -32768 to 32767)
- `np.int32`: integer(-2147483648 to 2147483647)
- `np.int64`:integer( -9223372036854775808 to 9223372036854775807)


Sometimes, you will need to load, create or export arrays from different data types.


## Harder exercises

The next exercises are related with real situations you could face while you are working in data science and machine learning. Also, we will be frequently talking about matrices and bidimensional arrays.

#### Exercise: Subtract the mean of each row of a matrix (★★☆)

#### Exercise: How to get the dates of yesterday, today and tomorrow? (★★☆)

>Check `np.datetime64`, `np.timedelta64` in numpy (https://numpy.org/doc/stable/reference/arrays.datetime.html)

#### Exercise: How to get all the dates corresponding to the month of December 2022? (★★☆)
Combine `arange`with `datetime`


#### Exercise: Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)

#### Exercise: Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### Exercise: Consider a generator function that generates 10 integers and use it to build an array (★★☆)

#### Exercise: Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### Exercise: Create a random vector of size 10 and sort it (★★☆)

#### Exercise: Consider two random arrays A and B, check if they are equal (★★☆)

#### Exercise: Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★★)
>Suggestion: check how to calculate the "square of a matrix"

#### Exercise: Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### Exercise: How to print all the values of an array? (★★☆)

#### Exercise: How to convert a float (32 bits) array into an integer (32 bits) in place?
>Check: https://stackoverflow.com/a/4396247/5989906

#### Exercise: Subtract the mean of each row of a matrix (★★☆)

#### Exercise: How to sort an array by the nth column? (★★☆)

#### Exercise: Find the position of the minimum of a 2D matrix (★★☆)

#### Exercise: Read an image using openCV, check its dimensions, normalize the numbers and show the image (★★★)

>Check: https://www.geeksforgeeks.org/python-opencv-cv2-imread-method/

#### Exercise: Considering a four dimensions array, how to get the sum over the last two axis at once? (★★★)

#### Exercise: How to get the diagonal of a dot product? (★★★)

#### Exercise: Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### Exercise: How to swap two rows of an array? (★★★)

#### Exercise: Read an image using openCV and tranpose it. What did you get exactly? Was the image rotated? Moved? Reflected with respect to an axis? (★★★)

#### Exercise: Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### Exercise: How to find the most frequent value in an array? (★★★)

#### Exercise: How to get the n largest values of an array (★★★)

#### Exercise: Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### Exercise: Given a two dimensional array, how to extract unique rows? (★★★)

#### Exercise: Can you have an array of strings? Can you mix different data types in the same array? Can you operate (add, sub, mult) arrays with different data types? (★★★)